# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'git practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for git practice
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firestore', :podspec => 'https://storage.googleapis.com/firebase-preview-drop/ios/firestore/0.7.0/Firestore.podspec.json'

end
